### PR TITLE
Update justinrainbow/json schema

### PR DESCRIPTION
**Pull request by smecnarowski**
I need this update because composer dependency conflict in another lib. Thanks

### CODE REVIEW

**Comment by ezzatron** [comment]
Whoops, I guess this got closed automatically when I axed the `develop` branch. I had to do a bit of repository maintenance, since this repo basically hasn't been touched in a couple of years. Sorry!

This should be fixed now. Could you please try `dev-master` and see if it solves your use case?

**Comment by smecnarowski** [comment]
Just checkad as alias "eloquent/composer-config-reader": "dev-master as 2.0.0" in composer and **it works**. I needed to do this with alias because your composer-config-reader is used by "magento-hackathon/magento-composer-installer". Maybe small tag update 2.0.1 ?

**Comment by ezzatron** [comment]
Released in [2.0.1](https://github.com/eloquent/composer-config-reader/releases/tag/2.0.1).

**Comment by smecnarowski** [comment]
thanks a lot!

**Comment by ezzatron** [comment]
No worries, thanks for the report!

**Pull request closed without merging**
