### PR TITLE
update justinrainbow/json-schema for php forward compatibility

### PR DESCRIPTION
**Pull request by Flyingmana**
Hi, I need the compatibility for another Project.

Did run the Tests locally with PHP 7.4 and they did run through

### CODE REVIEW

**Comment by ezzatron** [comment]
Hmm, looks like I hadn't gotten around to converting this project to use GitHub Actions instead of Travis CI. I'll try to get to it in the next couple of days.

**Comment by Flyingmana** [comment]
If you need help with this, I got a bit of routine with converting travisCI to github actions for php projects

maybe this example is already enough:
 https://github.com/Cotya/magento-composer-installer/blob/main/.github/workflows/integration.yml

**Comment by ezzatron** [comment]
That's okay, I've converted quite a few projects already, just not this one. I appreciate the offer though, thanks 🙂

**Comment by ezzatron** [comment]
Sorry, I had to fix this myself with a whole bunch of other dependency updates and other repo management. [3.0.0](https://github.com/eloquent/composer-config-reader/releases/tag/3.0.0) is now released which uses `json-schema@^5`. Note that it's still using the Composer 1 schema.

I'm going to look into how much the schema has changed for Composer 2. I may not be able to continue support for this library if the changes are extensive, so it may be worth considering removing your dependency on this library if possible. It's just fancy JSON parsing at the end of the day 🙃

**Pull request closed without merging**
